### ISSUE TITLE
Not all prerequisites completed when installing OpenSSL

### ISSUE THREAD

**Issue by ArseniiPetrovich** [poanetwork/deployment-playbooks#114]
While installing pyOpenSSL module there is a chance, that not all necessary packages already installed.
To avoid this i propose the following code changes for nginx role:

_Current:_
```
- name: Ensure python OpenSSL dependencies are installed.
  pip:
    name: pyOpenSSL
    state: present
```

_Fix:_
```
- name: Ensure OpenSSL dependencies are installed (Ubuntu)
  package:
     name: {{ item }}
     state: present
  with_items: 
    - build-essential
    - libssl-dev
    - libffi-dev
    - python-dev
  when: ansible_os_family == "Debian"
 
- name: Ensure OpenSSL dependencies are installed (CentOS)
  package:
     name: {{ item }}
     state: present
  with_items: 
    - gcc
    - libffi-devel
    - openssl-devel
    - python-devel
  when: ansible_os_family == "RedHat"

- name: Install OpenSSL module
  pip:
    name: pyOpenSSL
    state: present
```
