### ISSUE TITLE
Variables list

### ISSUE THREAD

**Issue by ArseniiPetrovich** [poanetwork/deployment-playbooks#129]
While preparing #125 I've spotted, that some code fragments declares lists with only one item, like:
```
- name: Install chrony package
  apt: name={{ item }}
  with_items:
    - chrony
```
The purpose of this issue is to rewrite them to be like:
```
- name: Install chrony package
  apt: name=chrony
```

Please, correct if I'm wrong and it was done on purpose.
