### ISSUE TITLE
Update CI config

### ISSUE THREAD

**Issue by ArseniiPetrovich** [poanetwork/deployment-playbooks#168]
As for https://github.com/poanetwork/deployment-terraform/pull/50 CI now requires additional environment variable that should be set by default. 
Now jobs `build` and `destroy` should have additional lines in `.circleci/config.yml`
Before:
```
  destroy:
    docker:
      - image: poanetwork/terraform-prep
    working_directory: ~/deployment-terraform/azure
```
After:
```
  destroy:
    docker:
      - image: poanetwork/terraform-prep
    working_directory: ~/deployment-terraform/azure
    environment:
          ANSIBLE_AZURE_AUTH_SOURCE: env
```
