### ISSUE TITLE
Update the way nodejs installed on Ubuntu

### ISSUE THREAD

**Issue by ArseniiPetrovich** [poanetwork/deployment-playbooks#189]
On `deployment-playbooks` we use this approach on installing nodejs 8:
```
- name: add nodejs repository key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 68576280
    state: present

- name: Add nodejs repository
  apt_repository:
    repo: 'deb {{ NODE_SOURCE_DEB }} {{ansible_distribution_release}} main'
    state: present
```
It doesn't work anymore since nodejs LTS key 68576280 is not relevant. To fix this I propose to change the code to the following, that we use at `deployment-terraform`
```
- name: Install the gpg key for nodejs LTS
  become: yes
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Install the nodejs LTS repos
  become: yes
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ node_version }}.x {{ ansible_distribution_release }} main"
    state: present
```
