### ISSUE TITLE
Ubuntu 18 compatibility: SSHD configuration

### ISSUE THREAD

**Issue by ArseniiPetrovich** [poanetwork/deployment-playbooks#194]
As we discovered during the installation process `deployment-playbooks` are not fully compatible with Ubuntu 18. The following code breaks the SSH server on the node making it isolated for any further connections: 
```
- name: Fix ssh Ciphers
  blockinfile:
    path: /etc/ssh/sshd_config
    insertafter: '^ServerKeyBits'
    content: |
      Ciphers aes256-ctr,aes192-ctr,aes128-ctr
      MACs hmac-sha1,hmac-ripemd160
  notify:
    - restart sshd
```
The roots of that issue lies in fact that starting from OpenSSH 7.6 insecure `hmac-ripemd160` MAC were removed. This issue is a point to reconsider MACs that should be used now.
